repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        stages: [manual]
      - id: end-of-file-fixer
        stages: [manual]
      - id: check-yaml
        stages: [manual]
      - id: check-added-large-files
        stages: [manual]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        stages: [manual]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        stages: [manual]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
        args: [--exit-zero]
        stages: [manual]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-python-dateutil
          - types-PyYAML
        args: [--ignore-missing-imports, --no-strict-optional]
        stages: [manual]
